// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DtKjZ_2Sv81FxLXXYnNdkgcCsazlfLM',
    appId: '1:683796707357:web:d890311ec7b68cd094aef4',
    messagingSenderId: '683796707357',
    projectId: 'flutter-agora-video-call-23afa',
    authDomain: 'flutter-agora-video-call-23afa.firebaseapp.com',
    storageBucket: 'flutter-agora-video-call-23afa.firebasestorage.app',
    measurementId: 'G-696CKVBWPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtmoeYKVAB_zYX9uqunIfRsSTK2U2nKLA',
    appId: '1:683796707357:android:671b9b461c8329ae94aef4',
    messagingSenderId: '683796707357',
    projectId: 'flutter-agora-video-call-23afa',
    storageBucket: 'flutter-agora-video-call-23afa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgZYfiZOpvpS6JjdGWISuI_m42bjvQoxs',
    appId: '1:683796707357:ios:e452a55a287b1dc394aef4',
    messagingSenderId: '683796707357',
    projectId: 'flutter-agora-video-call-23afa',
    storageBucket: 'flutter-agora-video-call-23afa.firebasestorage.app',
    iosBundleId: 'com.example.flutterAgoraVideoCall',
  );
}
